### ISSUE TITLE
Bookmark apps quit working with 10.0.8 Owncloud update.

### ISSUE THREAD

**Issue by Heetered** [mondjunge/bookmarks#5] opened 2018-05-14 01:59 UTC
Hi

Owncloud version 10.0.8 broke the bookmark server app. 

Can you please update app, none of the android and chrome apps relying on this server app are working.

Regards

**Comment by theScrabi** [comment] 2018-05-14 10:07
duplicate of https://github.com/mondjunge/bookmarks/issues/4

**Closed by theScrabi** 2018-05-14 10:07 UTC
Labels: duplicate
